export const SKILL_LIST = [
  "communication",
  "teamwork",
  "leadership",
  "problem solving",
  "critical thinking",
  "time management",
  "adaptability",
  "decision making",
  "analytical thinking",
  "creativity",
  "collaboration",
  "negotiation",
  "conflict resolution",
  "emotional intelligence",

  "microsoft excel",
  "microsoft word",
  "microsoft powerpoint",
  "microsoft project",
  "data analysis",
  "reporting",
  "documentation",
  "presentation skills",

  "project management",
  "business analysis",
  "stakeholder management",
  "strategic planning",
  "operations management",
  "process improvement",
  "risk management",
  "agile",
  "scrum",
  "product management",
  "forecasting",
  "vendor management",
  "contract negotiation",

  "digital marketing",
  "seo",
  "social media marketing",
  "content marketing",
  "lead generation",
  "crm",
  "sales strategy",
  "brand management",
  "copywriting",

  "financial analysis",
  "budgeting",
  "accounting",
  "taxation",
  "auditing",
  "cost management",
  "tally",
  "gst",

  "supply chain management",
  "inventory management",
  "logistics",
  "procurement",

  "recruitment",
  "talent acquisition",
  "employee engagement",
  "performance management",
  "hr operations",
  "payroll",

  "research",
  "data interpretation",
  "quality assurance",
  "quality control",
  "compliance",
  "testing",

  "erp",
  "sap",
  "sas",
  "salesforce",
  "zoho",
  "power bi",
  "tableau",
  "jira",
  "trello",
  "asana",
  "notion",
  "figma",
  "canva",

  "javascript",
  "python",
  "java",
  "c++",
  "c#",
  "typescript",
  "react",
  "node.js",
  "express",
  "mongodb",
  "sql",
  "mysql",
  "postgresql",
  "firebase",
  "rest api",
  "graphql",
  "git",
  "docker",
  "kubernetes",
  "aws",
  "azure",
  "gcp",
  "cloud computing",
  "linux",
  "html",
  "css",
  "tailwind",
  "bootstrap",
  "next.js",
  "vue.js",

  "artificial intelligence",
  "machine learning",
  "deep learning",
  "nlp",
  "computer vision",
  "data science",
  "automation",
  "cybersecurity",
  "blockchain",
  "iot",

  "kpi",
  "roi",
  "process optimization",
  "client handling",
  "customer satisfaction",
  "business growth",
];

export const REGEX_PATTERNS = {
  email: /[a-zA-Z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}/gi,

  phone:
    /(?:\(?\d{3}\)?[\s\-]?\d{3}[\s\-]?\d{4})|(?:(?:\+91[\s-]?)?[6-9]\d{9})|(?:\+\d{1,3}[\s-]?\d{6,14})/g,

  linkedin: /(?:linkedin\.com\/in\/|linkedin:\s*)([A-Za-z0-9\-_%]+)/i,
  github: /(?:github\.com\/|github:\s*)([A-Za-z0-9\-_%]+)/i,
  website:
    /(?:portfolio|website|site|web)[\s:\-]*([https://www\.][A-Za-z0-9\-._~:/?#[\]@!$&'()*+,;=%]+)/i,
  twitter: /(?:twitter\.com\/|twitter:\s*@?|x\.com\/)([A-Za-z0-9_]+)/i,

  location: /\b([A-Za-z\s]+),\s*([A-Za-z\s]+)(?:,\s*([A-Za-z\s]+))?\b/,

  locationKeywords:
    /buffalo|new\s*york|albany|rochester|manhattan|brooklyn|bronx|queens|staten\s*island|ahmedabad|surat|baroda|vadodara|rajkot|gandhinagar|mumbai|pune|delhi|bangalore|bengaluru|hyderabad|chennai|kolkata|jaipur|india|gujarat|maharashtra|karnataka|tamil\s*nadu|west\s*bengal/i,

  nameSkipPatterns: [
    /@/,
    /\d{5,}/,
    /http|www\.|linkedin|github/i,
    /resume|cv|curriculum/i,
  ],
  validName: /^[A-Za-z]+([\s'\-][A-Za-z]+){0,4}$/,

  summaryHeaders: [
    /^summary$/i,
    /^objective$/i,
    /^profile$/i,
    /^about\s*me$/i,
    /^overview$/i,
    /^professional\s*summary$/i,
    /^career\s*(objective|summary|profile)/i,
  ],

  education: [
    /^education$/i,
    /academic\s*(background|qualifications?)?/i,
    /^qualifications?$/i,
    /^degrees?$/i,
  ],

  experience: [
    /work\s*experience/i,
    /^experience$/i,
    /employment(\s*history)?/i,
    /professional\s*experience/i,
  ],

  experienceExit:
    /^(education|skills|projects|certifications|references|awards|achievements|leadership|honors|activities|volunteer|publications|languages)/i,

  projects: [/^projects?$/i, /personal\s*projects?/i, /academic\s*projects?/i],

  certifications: [
    /certifications?/i,
    /licenses?\s*&?\s*certifications?/i,
    /courses?/i,
    /training/i,
  ],

  languages: [/^languages?$/i, /language\s*skills?/i],

  defaultSectionExit:
    /^(experience|employment|work\s*history|skills|projects|certifications|education|references|awards|achievements|leadership|honors|activities|volunteer|publications|languages)/i,
};

export const STOP_WORDS = new Set([
  "a",
  "an",
  "the",
  "and",
  "or",
  "but",
  "in",
  "on",
  "at",
  "to",
  "for",
  "of",
  "with",
  "by",
  "from",
  "is",
  "was",
  "are",
  "were",
  "be",
  "been",
  "being",
  "have",
  "has",
  "had",
  "do",
  "does",
  "did",
  "will",
  "would",
  "could",
  "should",
  "may",
  "might",
  "shall",
  "can",
  "not",
  "no",
  "nor",
  "so",
  "yet",
  "both",
  "either",
  "neither",
  "each",
  "few",
  "more",
  "most",
  "other",
  "some",
  "such",
  "than",
  "then",
  "that",
  "this",
  "these",
  "those",
  "as",
  "if",
  "while",
  "after",
  "before",
  "about",
  "up",
  "out",
  "its",
  "it",
  "he",
  "she",
  "they",
  "we",
  "i",
  "you",
  "who",
  "which",
  "what",
]);


export const SECTION_HEADER_WORDS = new Set([
  "EDUCATION",
  "EXPERIENCE",
  "SKILLS",
  "PROJECTS",
  "CERTIFICATIONS",
  "LANGUAGES",
  "HONORS",
  "AWARDS",
  "REFERENCES",
  "SUMMARY",
  "OBJECTIVE",
  "PROFILE",
  "OVERVIEW",
  "LEADERSHIP",
  "ACTIVITIES",
  "VOLUNTEER",
  "PUBLICATIONS",
  "TRAINING",
  "COURSES",
  "ACHIEVEMENTS",
  "EMPLOYMENT",
]);